PERF: Revert multiprocessing start method change introduced in Python 3.14
Refs: https://github.com/python/cpython/issues/84559

Fixes CI failing on TestDocs.test_examples:

    ModuleNotFoundError: No module named '<run_path>'